name: Build Blender Add-on ZIP

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build_zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set version
        run: echo "RELEASE_VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV

      - name: Build Blender ZIP
        run: |
          mkdir -p release
          zip -r release/NFS-HELPER-${RELEASE_VERSION}.zip . \
            -x ".git/*" ".github/*" "docs/*" "*.gitignore" "LICENSE" "workflows/*"

      - name: Upload release ZIP
        uses: softprops/action-gh-release@v2
        with:
          files: release/NFS-HELPER-${RELEASE_VERSION}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}