name: Build Blender Add-on ZIP

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build_zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Blender ZIP
        run: |
          mkdir -p release
          zip -r release/NFS-HELPER-${GITHUB_REF_NAME}.zip nfs_helper

      - name: Debug
        run: ls -l release

      - name: Upload release ZIP
        uses: softprops/action-gh-release@v2
        with:
          files: release/NFS-HELPER-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}